'use client';
import { useActionState, useEffect, useRef, useState } from 'react';
import { Pencil, Plus, Trash2 } from 'lucide-react';
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from '@/components/ui/dialog';
import { createAuditStakeholderAction, deleteAuditStakeholderAction, updateAuditStakeholderAction, type StakeholderActionState } from '@/lib/operations-audits/actions';
const initial: StakeholderActionState={success:false};
type Stakeholder={id:string;name:string;role:string|null;department:string|null;seniority:string|null;responsibilities:string|null;interviewStatus:'NOT_PLANNED'|'PLANNED'|'INTERVIEWED'|'FOLLOW_UP';notes:string|null;_count:{ownedProcesses:number;processLinks:number;tasks:number}};
export function AuditStakeholdersRegistry({auditId,stakeholders}:{auditId:string;stakeholders:Stakeholder[]}){
 const [state,action,pending]=useActionState(createAuditStakeholderAction,initial);const ref=useRef<HTMLFormElement>(null);useEffect(()=>{if(state.success)ref.current?.reset()},[state]);
 return <div className="operations-systems"><form action={action} className="operations-system-quick" ref={ref}><input name="auditId" type="hidden" value={auditId}/><label className="manual-intake-admin-field"><span>Name *</span><input className="admin-input" maxLength={160} name="name" required/></label><label className="manual-intake-admin-field"><span>Role</span><input className="admin-input" name="role"/></label><label className="manual-intake-admin-field"><span>Department</span><input className="admin-input" name="department"/></label><button className="admin-button" disabled={pending}><Plus size={14}/>Adicionar</button>{state.error?<p className="project-form-error">{state.error}</p>:null}{state.message?<p className="admin-row-meta">{state.message}</p>:null}</form>
 {stakeholders.length?<div className="operations-system-list">{stakeholders.map(s=><StakeholderRow auditId={auditId} key={s.id} stakeholder={s}/>)}</div>:<div className="operations-steps-empty"><strong>Ainda não existem stakeholders.</strong><span>Capture pessoas, equipas ou papéis operacionais relevantes.</span></div>}</div>;
}
function StakeholderRow({auditId,stakeholder:s}:{auditId:string;stakeholder:Stakeholder}){const[state,action,pending]=useActionState(deleteAuditStakeholderAction,initial);return <article className="operations-system-row"><div><strong>{s.name}</strong><span>{s.role??'Role por definir'}{s.department?` · ${s.department}`:''} · {statusLabel(s.interviewStatus)}</span></div><div className="operations-system-usage"><span>{s._count.ownedProcesses} owned</span><span>{s._count.processLinks} processes</span><span>{s._count.tasks} steps</span></div><div className="operations-step-actions"><Edit auditId={auditId} stakeholder={s}/><form action={action} onSubmit={e=>{if(!window.confirm(`Apagar “${s.name}”?`))e.preventDefault()}}><input name="auditId" type="hidden" value={auditId}/><input name="stakeholderId" type="hidden" value={s.id}/><button aria-label={`Apagar ${s.name}`} className="project-icon-button operations-step-delete" disabled={pending}><Trash2 size={14}/></button></form></div>{state.error?<p className="project-form-error operations-system-row-error">{state.error}</p>:null}</article>}
function Edit({auditId,stakeholder:s}:{auditId:string;stakeholder:Stakeholder}){const[open,setOpen]=useState(false);const[state,action,pending]=useActionState(updateAuditStakeholderAction,initial);useEffect(()=>{if(state.success)setOpen(false)},[state]);return <Dialog open={open} onOpenChange={setOpen}><DialogTrigger asChild><button aria-label={`Editar ${s.name}`} className="project-icon-button"><Pencil size={14}/></button></DialogTrigger><DialogContent className="operations-process-dialog"><DialogHeader><DialogTitle>{s.name}</DialogTitle><DialogDescription>Contexto operacional, sem criar um perfil de RH.</DialogDescription></DialogHeader><form action={action} className="operations-process-form"><input name="auditId" type="hidden" value={auditId}/><input name="stakeholderId" type="hidden" value={s.id}/><div className="admin-grid-2"><Field name="name" label="Name *" value={s.name}/><Field name="role" label="Role" value={s.role}/></div><Field name="department" label="Department" value={s.department}/><details className="operations-step-details" open><summary>Audit context</summary><div className="operations-step-details-body"><Field name="seniority" label="Seniority" value={s.seniority}/><label className="manual-intake-admin-field"><span>Responsibilities</span><textarea className="admin-textarea" defaultValue={s.responsibilities??''} name="responsibilities"/></label><label className="manual-intake-admin-field"><span>Interview status</span><select className="admin-input" defaultValue={s.interviewStatus} name="interviewStatus"><option value="NOT_PLANNED">Not planned</option><option value="PLANNED">Planned</option><option value="INTERVIEWED">Interviewed</option><option value="FOLLOW_UP">Follow-up</option></select></label><label className="manual-intake-admin-field"><span>Notes</span><textarea className="admin-textarea" defaultValue={s.notes??''} name="notes"/></label></div></details>{state.error?<p className="project-form-error">{state.error}</p>:null}<div className="operations-process-form-actions"><button className="admin-button admin-button-muted" onClick={()=>setOpen(false)} type="button">Cancelar</button><button className="admin-button" disabled={pending}>Guardar</button></div></form></DialogContent></Dialog>}
function Field({name,label,value}:{name:string;label:string;value:string|null}){return <label className="manual-intake-admin-field"><span>{label}</span><input className="admin-input" defaultValue={value??''} maxLength={160} name={name} required={name==='name'}/></label>}
function statusLabel(v:Stakeholder['interviewStatus']){return({NOT_PLANNED:'Not planned',PLANNED:'Planned',INTERVIEWED:'Interviewed',FOLLOW_UP:'Follow-up'})[v]}
