'use client';
import Link from 'next/link';
import { useMemo, useState } from 'react';
import { ArrowUpRight } from 'lucide-react';
import { AdminBadge } from '@/components/admin/AdminBadge';
import { AdminEmptyState, AdminTable } from '@/components/admin/AdminPrimitives';
import { statusLabel } from './ProcessOpportunities';
import { displayPortfolioScore } from '@/lib/operations-audits/portfolio-ranking';
import type { MatrixDecision } from '@/lib/operations-audits/matrix-framework';

type Dimension = { score: number | null; coverage: number | null };
export type PortfolioOpportunity = { id: string; title: string; problem: string; proposedOutcome?: string | null; process: { id: string; name: string }; status: string; strategicFit: string | null; createdAt: string; scoredAt: string | null; score: number | null; confidence: number | null; coverage: number | null; dimensions: Record<string, Dimension> | null; decision: MatrixDecision; decisionState: string; decidedAt: string | null; scored: boolean; stale: boolean; globalRank: number | null };
type Sort = 'created' | 'title' | 'process' | 'score' | 'confidence' | 'coverage' | 'status' | 'scoredAt'; type Mode = 'PORTFOLIO' | 'RANKED' | 'MATRIX';

export function OpportunityPortfolio({ auditId, opportunities }: { auditId: string; opportunities: PortfolioOpportunity[] }) {
  const [mode, setMode] = useState<Mode>('PORTFOLIO'); const [search, setSearch] = useState(''); const [processId, setProcessId] = useState('ALL'); const [status, setStatus] = useState('ALL'); const [fit, setFit] = useState('ALL'); const [scoreState, setScoreState] = useState('ALL'); const [framework, setFramework] = useState('ALL'); const [decisionFilter, setDecisionFilter] = useState('ALL'); const [sort, setSort] = useState<Sort>('created'); const [selected, setSelected] = useState<string[]>([]); const [compareOpen, setCompareOpen] = useState(false);
  const processes = useMemo(() => Array.from(new Map(opportunities.map((x) => [x.process.id, x.process])).values()).sort((a, b) => a.name.localeCompare(b.name)), [opportunities]);
  const rows = useMemo(() => opportunities.filter((x) => { const q = search.trim().toLocaleLowerCase(); return (!q || `${x.title} ${x.problem} ${x.process.name}`.toLocaleLowerCase().includes(q)) && (processId === 'ALL' || x.process.id === processId) && (status === 'ALL' || x.status === status) && (fit === 'ALL' || (fit === 'NONE' ? x.strategicFit === null : x.strategicFit === fit)) && (scoreState === 'ALL' || (scoreState === 'SCORED' && x.scored) || (scoreState === 'UNSCORED' && !x.scored) || (scoreState === 'STALE' && x.stale)) && (framework === 'ALL' || x.decision.classification === framework) && (decisionFilter === 'ALL' || x.decisionState === decisionFilter); }).sort(comparator(sort)), [opportunities, search, processId, status, fit, scoreState, framework, decisionFilter, sort]);
  const ranked = rows.filter((x) => x.globalRank !== null); const unranked = rows.filter((x) => x.globalRank === null); const selectedRows = opportunities.filter((x) => selected.includes(x.id)); const scored = opportunities.filter((x) => x.scored).length; const stale = opportunities.filter((x) => x.stale).length;
  const counts = opportunities.reduce<Record<string, number>>((acc, row) => { acc[row.decision.classification] = (acc[row.decision.classification] ?? 0) + 1; return acc; }, {});
  const toggle = (id: string) => setSelected((current) => current.includes(id) ? current.filter((value) => value !== id) : current.length >= 4 ? current : [...current, id]);
  return <div className="operations-systems"><div className="admin-kpi-grid"><Fact label="Total Opportunities" value={opportunities.length} /><Fact label="Scored" value={scored} /><Fact label="Ranked" value={opportunities.filter((x) => x.globalRank !== null).length} /><Fact label="Decision-ready" value={opportunities.filter((x) => x.decision.decisionReady).length} /><Fact label="Needs validation" value={(counts.NEEDS_VALIDATION ?? 0)} /><Fact label="Needs recalculation" value={stale} /></div>
    {opportunities.length ? <><div className="admin-filters"><Select label="View" value={mode} onChange={(value) => setMode(value as Mode)}><option value="PORTFOLIO">Portfolio</option><option value="RANKED">Ranked view</option><option value="MATRIX">Matrix</option></Select><input aria-label="Pesquisar oportunidades" className="admin-input" onChange={(e) => setSearch(e.target.value)} placeholder="Search title, problem or process…" value={search} /><Select label="Process" value={processId} onChange={setProcessId}><option value="ALL">All processes</option>{processes.map((x) => <option key={x.id} value={x.id}>{x.name}</option>)}</Select><Select label="Status" value={status} onChange={setStatus}><option value="ALL">All statuses</option>{['DISCOVERED', 'VALIDATING', 'RECOMMENDED', 'PILOT_PROPOSED', 'PILOT_ACCEPTED', 'IMPLEMENTED', 'REJECTED'].map((x) => <option key={x} value={x}>{statusLabel(x)}</option>)}</Select><Select label="Strategic Fit" value={fit} onChange={setFit}><option value="ALL">All fits</option><option value="HIGH">High</option><option value="MEDIUM">Medium</option><option value="LOW">Low</option><option value="NONE">Not defined</option></Select><Select label="Framework" value={framework} onChange={setFramework}><option value="ALL">All classifications</option>{frameworkOptions.map((x) => <option key={x.value} value={x.value}>{x.label}</option>)}</Select><Select label="Score State" value={scoreState} onChange={setScoreState}><option value="ALL">All score states</option><option value="SCORED">Scored</option><option value="UNSCORED">Unscored</option><option value="STALE">Stale</option></Select><Select label="Sort" value={sort} onChange={(value) => setSort(value as Sort)}><option value="created">Newest created</option><option value="title">Title A–Z</option><option value="process">Process A–Z</option><option value="score">Score high–low</option><option value="confidence">Confidence high–low</option><option value="coverage">Coverage high–low</option><option value="status">Status A–Z</option><option value="scoredAt">Most recently scored</option></Select></div>
      {mode === 'RANKED' ? <p className="admin-row-meta">Rank reflects the scoring model only. Framework classification, evidence and human decision fields remain separate.</p> : null}
      {mode === 'MATRIX' ? <><MatrixHelp /><MatrixView rows={rows} /><div className="admin-filters"><span className="admin-row-meta">Decision-ready means only that the evidence gates passed; it does not mean ready to implement.</span></div></> : <><div className="admin-filters"><button className="admin-button admin-button-muted" disabled={selected.length < 2} onClick={() => setCompareOpen(true)}>Compare selected ({selected.length}/4)</button><span className="admin-row-meta">Select up to four opportunities. Comparison stays within this audit.</span></div>{mode === 'RANKED' ? <>{ranked.length ? <OpportunityTable rows={ranked} auditId={auditId} ranked selectable selected={selected} toggle={toggle} /> : <AdminEmptyState>No opportunities have a calculable score yet. Evaluate and calculate opportunities to enable ranking.</AdminEmptyState>}{unranked.length ? <><h3 className="admin-section-title">Unranked</h3><OpportunityTable rows={unranked} auditId={auditId} selectable selected={selected} toggle={toggle} /></> : null}</> : rows.length ? <OpportunityTable rows={rows} auditId={auditId} selectable selected={selected} toggle={toggle} /> : <AdminEmptyState>No opportunities match the current filters.</AdminEmptyState>}{compareOpen ? <Comparison rows={selectedRows} auditId={auditId} close={() => setCompareOpen(false)} /> : null}</>}</> : <AdminEmptyState><div className="operations-process-empty"><strong>No automation opportunities identified yet.</strong><span>Create opportunities from processes where bottlenecks and baseline evidence have been captured.</span><a className="admin-link" href="#processes">View processes</a></div></AdminEmptyState>}
  </div>;
}

const frameworkOptions = [{ value: 'QUICK_WIN_CANDIDATE', label: 'Quick Win Candidate' }, { value: 'STRATEGIC_BET_CANDIDATE', label: 'Strategic Bet Candidate' }, { value: 'SELECTIVE_OPPORTUNITY', label: 'Selective Opportunity' }, { value: 'LOWER_PRIORITY_CANDIDATE', label: 'Lower Priority Candidate' }, { value: 'NEEDS_VALIDATION', label: 'Needs Validation' }, { value: 'NEEDS_RECALCULATION', label: 'Needs Recalculation' }, { value: 'NEEDS_EVALUATION', label: 'Needs Evaluation' }];
function OpportunityTable({ rows, auditId, ranked = false, selectable, selected, toggle }: { rows: PortfolioOpportunity[]; auditId: string; ranked?: boolean; selectable: boolean; selected: string[]; toggle: (id: string) => void }) { return <AdminTable headers={[...(selectable ? ['Select'] : []), ...(ranked ? ['Rank'] : []), 'Opportunity', 'Process', 'Score', 'Framework', 'Confidence', 'Coverage', 'Strategic Fit', 'Status', 'Score State', '']}><>{rows.map((x) => <tr key={x.id}>{selectable ? <td><input aria-label={`Select ${x.title} for comparison`} type="checkbox" checked={selected.includes(x.id)} disabled={!selected.includes(x.id) && selected.length >= 4} onChange={() => toggle(x.id)} /></td> : null}{ranked ? <td>{x.globalRank === null ? '—' : `#${x.globalRank}`}</td> : null}<td><strong className="finance-table-title">{x.title}</strong><span className="finance-table-meta">{x.problem}</span></td><td><Link className="admin-link" href={`/admin/operations-audits/${auditId}/processes/${x.process.id}`}>{x.process.name}</Link></td><td>{x.scored ? displayPortfolioScore(x.score) + (x.score === null ? '' : ' / 100') : 'Not scored'}</td><td><AdminBadge title={x.decision.reason} tone={x.decision.decisionReady ? 'blue' : 'yellow'}>{x.decision.label}</AdminBadge></td><td>{x.scored && x.confidence !== null ? `${Math.round(x.confidence)}%` : '—'}</td><td>{x.scored && x.coverage !== null ? `${Math.round(x.coverage)}%` : '—'}</td><td><AdminBadge tone="slate">{fitLabel(x.strategicFit)}</AdminBadge></td><td><AdminBadge tone={x.status === 'RECOMMENDED' ? 'green' : x.status === 'VALIDATING' ? 'blue' : 'slate'}>{statusLabel(x.status)}</AdminBadge></td><td><AdminBadge tone={x.stale ? 'yellow' : x.scored ? 'blue' : 'slate'}>{x.stale ? 'Needs recalculation' : x.scored ? 'Current' : 'Unscored'}</AdminBadge></td><td><Link aria-label={`Abrir ${x.title}`} className="admin-link finance-table-link" href={`/admin/operations-audits/${auditId}/processes/${x.process.id}/opportunities/${x.id}`}>Abrir <ArrowUpRight size={13} /></Link></td></tr>)}</></AdminTable>; }
function MatrixView({ rows }: { rows: PortfolioOpportunity[] }) { const groups = new Map<string, PortfolioOpportunity[]>(); for (const row of rows) { const key = row.decision.matrixPosition ?? 'UNPLACED'; groups.set(key, [...(groups.get(key) ?? []), row]); } const quadrant = (key: string, title: string, description: string) => <section className="admin-panel" key={key}><h3>{title}</h3><p className="admin-row-meta">{description}</p>{(groups.get(key) ?? []).length ? <ul>{(groups.get(key) ?? []).map((x) => <li key={x.id}><strong>{x.title}</strong> <span className="admin-row-meta">BV {displayPortfolioScore(x.dimensions?.businessValue?.score ?? null)} · Feasibility {displayPortfolioScore(x.dimensions?.feasibility?.score ?? null)}</span></li>)}</ul> : <p className="admin-row-meta">No opportunities in this quadrant.</p>}</section>; return <><div className="admin-grid-2"><div className="admin-panel"><p className="admin-field-label">Business Value ↑</p><div className="admin-grid-2">{quadrant('LOW_LOW', 'Lower Priority Candidate', 'Lower value · lower feasibility')}{quadrant('HIGH_LOW', 'Strategic Bet Candidate', 'Higher value · lower feasibility')}{quadrant('LOW_HIGH', 'Selective Opportunity', 'Lower value · higher feasibility')}{quadrant('HIGH_HIGH', 'Quick Win Candidate', 'Higher value · higher feasibility')}</div><p className="admin-field-label">Automation Feasibility →</p></div><div className="admin-panel"><h3>Matrix position</h3><p className="admin-row-meta">Each opportunity is placed using persisted Business Value and Automation Feasibility dimension scores. Points remain fixed-size and are also listed textually for accessibility.</p></div></div><div className="admin-panel"><h3>Needs attention</h3>{(groups.get('UNPLACED') ?? []).length ? <ul>{(groups.get('UNPLACED') ?? []).map((x) => <li key={x.id}><strong>{x.title}</strong> — {x.decision.label}: {x.decision.reason}</li>)}</ul> : <p className="admin-row-meta">No unplaced opportunities.</p>}</div></>; }
function MatrixHelp() { return <div className="admin-panel"><h3>How the framework works</h3><p className="admin-row-text">Business Value describes how valuable the problem appears to solve. Automation Feasibility describes how practical automation appears to implement. Evidence gates prevent quadrant labels when coverage or confidence is incomplete; these are V1 decision-framework thresholds, not scoring-model formulas.</p></div>; }
function Comparison({ rows, auditId, close }: { rows: PortfolioOpportunity[]; auditId: string; close: () => void }) { return <section className="admin-panel"><div className="admin-panel-header"><div><h3>Comparison</h3><p>Evidence-aware side-by-side view; no automatic winner or recommendation.</p></div><button className="admin-button admin-button-muted" onClick={close}>Close</button></div><div className="admin-table-wrap"><table className="admin-table"><thead><tr><th>Metric</th>{rows.map((x) => <th key={x.id}>{x.title}</th>)}</tr></thead><tbody>{[['Process', (x: PortfolioOpportunity) => x.process.name], ['Rank', (x: PortfolioOpportunity) => x.globalRank === null ? '—' : `#${x.globalRank}`], ['Matrix Classification', (x: PortfolioOpportunity) => `${x.decision.label}: ${x.decision.reason}`], ['Score', (x: PortfolioOpportunity) => x.scored ? displayPortfolioScore(x.score) : 'Not scored'], ['Business Value', (x: PortfolioOpportunity) => dimensionValue(x, 'businessValue')], ['Feasibility', (x: PortfolioOpportunity) => dimensionValue(x, 'feasibility')], ['Market Potential', (x: PortfolioOpportunity) => dimensionValue(x, 'marketPotential')], ['Confidence', (x: PortfolioOpportunity) => x.confidence === null ? '—' : `${Math.round(x.confidence)}%`], ['Coverage', (x: PortfolioOpportunity) => x.coverage === null ? '—' : `${Math.round(x.coverage)}%`], ['Strategic Fit', (x: PortfolioOpportunity) => fitLabel(x.strategicFit)], ['Status', (x: PortfolioOpportunity) => statusLabel(x.status)], ['Problem', (x: PortfolioOpportunity) => x.problem], ['Proposed outcome', (x: PortfolioOpportunity) => x.proposedOutcome || '—']].map(([label, getter]) => <tr key={String(label)}><th>{String(label)}</th>{rows.map((x) => <td key={x.id}>{(getter as (row: PortfolioOpportunity) => string)(x)}</td>)}</tr>)}<tr><th>Details</th>{rows.map((x) => <td key={x.id}><Link className="admin-link" href={`/admin/operations-audits/${auditId}/processes/${x.process.id}/opportunities/${x.id}`}>View full breakdown</Link></td>)}</tr></tbody></table></div></section>; }
function dimensionValue(row: PortfolioOpportunity, key: string) { const value = row.dimensions?.[key]; return !value || value.score === null ? '—' : `${displayPortfolioScore(value.score)} / 100${value.coverage === null ? '' : ` · ${Math.round(value.coverage)}% coverage`}`; }
function Select({ label, value, onChange, children }: { label: string; value: string; onChange: (value: string) => void; children: React.ReactNode }) { return <label className="manual-intake-admin-field"><span>{label}</span><select aria-label={label} className="admin-input" onChange={(e) => onChange(e.target.value)} value={value}>{children}</select></label>; }
function Fact({ label, value }: { label: string; value: number }) { return <div><p className="admin-field-label">{label}</p><p className="admin-row-title">{value}</p></div>; }
function fitLabel(value: string | null) { return value ? value[0] + value.slice(1).toLowerCase() : 'Not defined'; }
function comparator(sort: Sort) { return (a: PortfolioOpportunity, b: PortfolioOpportunity) => { if (sort === 'created') return Date.parse(b.createdAt) - Date.parse(a.createdAt); if (sort === 'title') return a.title.localeCompare(b.title); if (sort === 'process') return a.process.name.localeCompare(b.process.name) || a.title.localeCompare(b.title); if (sort === 'status') return a.status.localeCompare(b.status) || a.title.localeCompare(b.title); if (sort === 'scoredAt') return descending(a.scoredAt ? Date.parse(a.scoredAt) : null, b.scoredAt ? Date.parse(b.scoredAt) : null); if (sort === 'score') return descending(a.score, b.score); if (sort === 'confidence') return descending(a.confidence, b.confidence); return descending(a.coverage, b.coverage); }; }
function descending(a: number | null, b: number | null) { if (a === null && b === null) return 0; if (a === null) return 1; if (b === null) return -1; return b - a; }
