'use client';

import { useActionState } from 'react';
import { Save } from 'lucide-react';
import { saveOpportunityEvaluationAction,type EvaluationActionState } from '@/lib/operations-audits/actions';
import { criterionMetadata,dimensionMetadata,isCriterionKey,type AutomationAssessment,type CriterionKey,type ScoringModelConfig } from '@/lib/operations-audits/scoring';

const initial:EvaluationActionState={success:false};
type Model={id:string;name:string;version:number;config:ScoringModelConfig};
type Context={bottlenecks:{description:string}[];baselines:{label:string;value:string|null;unit:string|null;period:string|null;evidenceQuality:string}[];systems:{name:string;apiAvailable:string;exportAvailable:string;integrationDifficulty:string|null}[];dataSources:{name:string;structure:string|null;accessibility:string|null;quality:string|null;sensitivity:string|null}[]};

export function OpportunityEvaluation({auditId,processId,opportunityId,model,assessment,context}:{auditId:string;processId:string;opportunityId:string;model:Model;assessment:unknown;context:Context}){const[state,action,pending]=useActionState(saveOpportunityEvaluationAction,initial);const dimensions=Object.entries(model.config.dimensions);const configured=dimensions.flatMap(([,d])=>Object.keys(d.criteria)).filter(isCriterionKey);const known=configured.filter(key=>observation(assessment,key).value!==null).length;return <div className="operations-systems"><div className="admin-grid-2"><div><p className="admin-field-label">Evaluation model</p><p className="admin-row-title">{model.name}</p><p className="admin-row-meta">Version {model.version} · active configuration</p></div><div><p className="admin-field-label">Coverage</p><p className="admin-row-title">{known} / {configured.length} criteria assessed</p><p className="admin-row-meta">Unknown criteria remain explicitly unknown.</p></div></div><EvaluationContext context={context}/><form action={action} className="operations-process-form"><input name="auditId" type="hidden" value={auditId}/><input name="processId" type="hidden" value={processId}/><input name="opportunityId" type="hidden" value={opportunityId}/><input name="scoringModelId" type="hidden" value={model.id}/>{dimensions.map(([dimensionKey,dimension])=><section key={dimensionKey}><h3>{dimensionMetadata[dimensionKey as keyof typeof dimensionMetadata]?.label??dimensionKey}</h3><div className="operations-system-list">{Object.keys(dimension.criteria).filter(isCriterionKey).map(key=><CriterionRow assessment={assessment} criterionKey={key} key={key}/>)}</div></section>)}{state.error?<p className="project-form-error">{state.error}</p>:null}{state.success?<p className="admin-row-meta">Evaluation guardada sem calcular score.</p>:null}<div className="operations-process-form-actions"><button className="admin-button" disabled={pending}><Save size={14}/>Save Evaluation</button></div></form></div>}
function CriterionRow({criterionKey:key,assessment}:{criterionKey:CriterionKey;assessment:unknown}){const value=observation(assessment,key),meta=criterionMetadata[key];return <details className="operations-step-details"><summary><span><strong>{meta.label}</strong><small>{meta.anchor}</small></span><span>{value.value===null?'Unknown':`${value.value} / 5`} · {qualityLabel(value.evidenceQuality)}</span></summary><div className="operations-step-details-body"><div className="admin-grid-2"><label className="manual-intake-admin-field"><span>Value</span><select className="admin-input" defaultValue={value.value===null?'UNKNOWN':String(value.value)} name={`${key}.value`}><option value="UNKNOWN">Unknown</option>{[1,2,3,4,5].map(x=><option key={x} value={x}>{x} — {x===1?meta.anchor.split(' · ')[0].replace('1 = ',''):x===5?meta.anchor.split(' · ')[1]?.replace('5 = ',''):''}</option>)}</select></label><label className="manual-intake-admin-field"><span>Evidence Quality</span><select className="admin-input" defaultValue={value.evidenceQuality} name={`${key}.evidenceQuality`}><option value="UNKNOWN">Unknown</option><option value="ESTIMATED">Estimated</option><option value="MEASURED">Measured</option></select></label></div><div className="admin-grid-2"><Field label="Source" name={`${key}.source`} value={value.source}/><Field label="Reference" name={`${key}.reference`} value={value.reference}/></div><label className="manual-intake-admin-field"><span>Supporting Note</span><textarea className="admin-textarea" defaultValue={value.note??''} name={`${key}.note`}/></label><label className="manual-intake-admin-field"><span>Captured At</span><input className="admin-input" defaultValue={dateValue(value.capturedAt)} name={`${key}.capturedAt`} type="date"/></label></div></details>}
function EvaluationContext({context}:{context:Context}){return <details className="operations-step-details"><summary>Existing evidence context (does not auto-fill values)</summary><div className="operations-step-details-body"><div className="admin-grid-2"><ContextList title="Related bottlenecks" items={context.bottlenecks.map(x=>x.description)}/><ContextList title="Related baseline" items={context.baselines.map(x=>`${x.label}: ${x.value??'Unknown'}${x.unit?` ${x.unit}`:''}${x.period?` / ${x.period}`:''} · ${qualityLabel(x.evidenceQuality)}`)}/><ContextList title="Process systems" items={context.systems.map(x=>`${x.name} · API ${x.apiAvailable} · Export ${x.exportAvailable}${x.integrationDifficulty?` · ${x.integrationDifficulty}`:''}`)}/><ContextList title="Process data sources" items={context.dataSources.map(x=>`${x.name}${x.structure?` · ${x.structure}`:''}${x.accessibility?` · ${x.accessibility}`:''}${x.quality?` · ${x.quality}`:''}${x.sensitivity?` · ${x.sensitivity}`:''}`)}/></div></div></details>}
function ContextList({title,items}:{title:string;items:string[]}){return <div><p className="admin-field-label">{title}</p>{items.length?items.map((item,index)=><p className="admin-row-meta" key={`${item}-${index}`}>{item}</p>):<p className="admin-row-meta">No context captured.</p>}</div>}
function Field({label,name,value}:{label:string;name:string;value:string|null}){return <label className="manual-intake-admin-field"><span>{label}</span><input className="admin-input" defaultValue={value??''} name={name}/></label>}
function observation(raw:unknown,key:CriterionKey){const fallback={value:null,evidenceQuality:'UNKNOWN' as const,source:null,reference:null,note:null,capturedAt:null};if(!raw||typeof raw!=='object')return fallback;const candidate=(raw as Partial<AutomationAssessment>)[key];if(!candidate||typeof candidate!=='object')return fallback;const value=Number.isInteger(candidate.value)&&Number(candidate.value)>=1&&Number(candidate.value)<=5?Number(candidate.value):null;const evidenceQuality=['UNKNOWN','ESTIMATED','MEASURED'].includes(candidate.evidenceQuality)?candidate.evidenceQuality:'UNKNOWN';return{value,evidenceQuality,source:candidate.source??null,reference:candidate.reference??null,note:candidate.note??null,capturedAt:candidate.capturedAt??null}}
function qualityLabel(value:string){return value==='MEASURED'?'Measured':value==='ESTIMATED'?'Estimated':'Unknown evidence'}
function dateValue(value:string|null){return value?value.slice(0,10):''}
