'use client';

import { useActionState } from 'react';
import { Link2, X } from 'lucide-react';
import { linkBaselineToOpportunityAction,linkBottleneckToOpportunityAction,unlinkBaselineFromOpportunityAction,unlinkBottleneckFromOpportunityAction,updateAutomationOpportunityAction,type OpportunityActionState } from '@/lib/operations-audits/actions';
import { statusLabel } from './ProcessOpportunities';

const initial:OpportunityActionState={success:false};
type Bottleneck={id:string;description:string;category:string;task:{name:string;sequence:number}|null};
type Baseline={id:string;label:string;numericValue:unknown;unit:string|null;period:string|null};
type Opportunity={id:string;title:string|null;problem:string;currentState:string|null;proposedOutcome:string|null;automationConcept:string|null;expectedFutureState:string|null;status:string;recommendation:string|null;bottleneckLinks:{bottleneck:Bottleneck}[];baselineLinks:{baseline:Baseline}[]};

export function OpportunityDetail({auditId,processId,opportunity,bottlenecks,baselines}:{auditId:string;processId:string;opportunity:Opportunity;bottlenecks:Bottleneck[];baselines:Baseline[]}){const[state,action,pending]=useActionState(updateAutomationOpportunityAction,initial);return <div className="admin-page-grid"><form action={action} className="operations-process-form"><Ids auditId={auditId} processId={processId} opportunityId={opportunity.id}/><label className="manual-intake-admin-field"><span>Opportunity title *</span><input className="admin-input" defaultValue={opportunity.title??''} name="title" required/></label><label className="manual-intake-admin-field"><span>Problem *</span><textarea className="admin-textarea" defaultValue={opportunity.problem} name="problem" required/></label><details className="operations-step-details" open><summary>Opportunity definition</summary><div className="operations-step-details-body"><Area label="Current state" name="currentState" value={opportunity.currentState}/><Area label="Proposed outcome" name="proposedOutcome" value={opportunity.proposedOutcome}/><Area label="Automation concept" name="automationConcept" value={opportunity.automationConcept}/><Area label="Expected future state" name="expectedFutureState" value={opportunity.expectedFutureState}/></div></details><div className="admin-grid-2"><label className="manual-intake-admin-field"><span>Status</span><select className="admin-input" defaultValue={opportunity.status} name="status">{['DISCOVERED','VALIDATING','RECOMMENDED','PILOT_PROPOSED','PILOT_ACCEPTED','IMPLEMENTED','REJECTED'].map(x=><option key={x} value={x}>{statusLabel(x)}</option>)}</select></label><Area label="Recommendation" name="recommendation" value={opportunity.recommendation}/></div>{state.error?<p className="project-form-error">{state.error}</p>:null}{state.success?<p className="admin-row-meta">Guardado.</p>:null}<div className="operations-process-form-actions"><button className="admin-button" disabled={pending}>Guardar alterações</button></div></form><Evidence title="Bottlenecks" empty="Sem bottlenecks associados." options={bottlenecks.filter(x=>!opportunity.bottleneckLinks.some(y=>y.bottleneck.id===x.id)).map(x=>({id:x.id,label:x.description}))} links={opportunity.bottleneckLinks.map(x=>({id:x.bottleneck.id,label:x.bottleneck.description}))} idName="bottleneckId" linkAction={linkBottleneckToOpportunityAction} unlinkAction={unlinkBottleneckFromOpportunityAction} ids={{auditId,processId,opportunityId:opportunity.id}}/><Evidence title="Baseline metrics" empty="Sem baseline associada." options={baselines.filter(x=>!opportunity.baselineLinks.some(y=>y.baseline.id===x.id)).map(x=>({id:x.id,label:baselineLabel(x)}))} links={opportunity.baselineLinks.map(x=>({id:x.baseline.id,label:baselineLabel(x.baseline)}))} idName="baselineId" linkAction={linkBaselineToOpportunityAction} unlinkAction={unlinkBaselineFromOpportunityAction} ids={{auditId,processId,opportunityId:opportunity.id}}/></div>}
function Evidence({title,empty,options,links,idName,linkAction,unlinkAction,ids}:{title:string;empty:string;options:{id:string;label:string}[];links:{id:string;label:string}[];idName:'bottleneckId'|'baselineId';linkAction:(state:OpportunityActionState,data:FormData)=>Promise<OpportunityActionState>;unlinkAction:(data:FormData)=>Promise<void>;ids:{auditId:string;processId:string;opportunityId:string}}){const[state,action,pending]=useActionState(linkAction,initial);return <section><h3>{title}</h3><form action={action} className="operations-system-quick"><Ids {...ids}/><label className="manual-intake-admin-field"><span>Associar evidência</span><select className="admin-input" name={idName} required><option value="">Selecionar…</option>{options.map(x=><option key={x.id} value={x.id}>{x.label}</option>)}</select></label><button className="admin-button admin-button-muted" disabled={pending||!options.length}><Link2 size={14}/>Associar</button>{state.error?<p className="project-form-error">{state.error}</p>:null}</form>{links.length?<div className="operations-system-list">{links.map(x=><article className="operations-system-row" key={x.id}><div><strong>{x.label}</strong></div><form action={unlinkAction}><Ids {...ids}/><input name={idName} type="hidden" value={x.id}/><button aria-label="Desassociar evidência" className="project-icon-button"><X size={14}/></button></form></article>)}</div>:<p className="admin-row-meta">{empty}</p>}</section>}
function Ids({auditId,processId,opportunityId}:{auditId:string;processId:string;opportunityId:string}){return <><input name="auditId" type="hidden" value={auditId}/><input name="processId" type="hidden" value={processId}/><input name="opportunityId" type="hidden" value={opportunityId}/></>}
function Area({label,name,value}:{label:string;name:string;value:string|null}){return <label className="manual-intake-admin-field"><span>{label}</span><textarea className="admin-textarea" defaultValue={value??''} name={name}/></label>}
function baselineLabel(x:Baseline){return `${x.label}: ${x.numericValue===null?'Unknown':String(x.numericValue)}${x.unit?` ${x.unit}`:''}${x.period?` / ${x.period}`:''}`}
