'use client';
import { useActionState } from 'react';
import { updateHumanOpportunityDecisionAction, type DecisionActionState } from '@/lib/operations-audits/actions';
import { AdminBadge } from '@/components/admin/AdminBadge';
import type { MatrixDecision } from '@/lib/operations-audits/matrix-framework';

const initial: DecisionActionState = { success: false };
const decisionOptions = [['UNDECIDED', 'Undecided'], ['PROCEED_TO_PILOT', 'Proceed to Pilot'], ['NEEDS_MORE_VALIDATION', 'Needs More Validation'], ['HOLD', 'Hold'], ['REJECT', 'Reject']] as const;
export function OpportunityDecision({ auditId, processId, opportunityId, decision, decisionRationale, decisionOwner, decidedAt, nextStep, context }: { auditId: string; processId: string; opportunityId: string; decision: string; decisionRationale: string | null; decisionOwner: string | null; decidedAt: string | null; nextStep: string | null; context: { score: string; confidence: string; coverage: string; rank: string; matrix: MatrixDecision; strategicFit: string; status: string } }) {
  const [state, action, pending] = useActionState(updateHumanOpportunityDecisionAction, initial);
  const warning = context.matrix.classification === 'NEEDS_VALIDATION' || context.matrix.classification === 'NEEDS_RECALCULATION' || context.matrix.classification === 'NEEDS_EVALUATION';
  return <div className="admin-grid-2"><div><div className="admin-panel"><h3>Analytical context</h3><div className="admin-grid-2"><Fact label="Opportunity Score" value={context.score} /><Fact label="Confidence" value={context.confidence} /><Fact label="Coverage" value={context.coverage} /><Fact label="Rank" value={context.rank} /><Fact label="Matrix" value={context.matrix.label} /><Fact label="Strategic Fit" value={context.strategicFit} /><Fact label="Status" value={context.status} /></div><p className="admin-row-meta">These analytical signals remain separate from the human decision.</p></div>{warning ? <p className="project-form-error">This opportunity currently requires additional validation according to the decision framework. You can still proceed, but the decision should explain why.</p> : null}</div><form action={action} className="operations-process-form"><input name="auditId" type="hidden" value={auditId} /><input name="processId" type="hidden" value={processId} /><input name="opportunityId" type="hidden" value={opportunityId} /><label className="manual-intake-admin-field"><span>Decision</span><select aria-label="Decision" className="admin-input" defaultValue={decision} name="decision">{decisionOptions.map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label className="manual-intake-admin-field"><span>Decision Rationale {decision !== 'UNDECIDED' ? '*' : ''}</span><textarea aria-label="Decision Rationale" className="admin-textarea" defaultValue={decisionRationale ?? ''} name="decisionRationale" placeholder="Explain why this human decision was made." /></label><label className="manual-intake-admin-field"><span>Decision Owner</span><input aria-label="Decision Owner" className="admin-input" defaultValue={decisionOwner ?? ''} name="decisionOwner" placeholder="Name or internal owner" /></label><label className="manual-intake-admin-field"><span>Next Step</span><textarea aria-label="Next Step" className="admin-textarea" defaultValue={nextStep ?? ''} name="nextStep" placeholder="What still needs to happen next?" /></label>{decidedAt ? <p className="admin-row-meta">Decision date: {new Date(decidedAt).toLocaleString('pt-PT')}</p> : <p className="admin-row-meta">No final decision has been recorded.</p>}{state.error ? <p className="project-form-error">{state.error}</p> : null}{state.success ? <p className="admin-row-meta">Decision saved. Analytical scores and status were not changed.</p> : null}<div className="operations-process-form-actions"><button className="admin-button" disabled={pending}>{decision === 'UNDECIDED' ? 'Save Draft' : 'Finalize Decision'}</button></div></form></div>;
}
function Fact({ label, value }: { label: string; value: string }) { return <div><p className="admin-field-label">{label}</p><p className="admin-row-title">{value}</p></div>; }
