'use client';
import { useActionState, useEffect, useRef } from 'react';
import { Plus, Unlink } from 'lucide-react';
import { createAndLinkStakeholderToProcessAction, linkStakeholderToProcessAction, setProcessOwnerStakeholderAction, unlinkStakeholderFromProcessAction, type StakeholderActionState } from '@/lib/operations-audits/actions';
const initial:StakeholderActionState={success:false};type Person={id:string;name:string;role:string|null;department:string|null};
export function ProcessStakeholders({auditId,processId,stakeholders,owner,participants}:{auditId:string;processId:string;stakeholders:Person[];owner:Person|null;participants:Person[]}){
 const linked=new Set(participants.map(p=>p.id));return <div className="operations-process-systems"><Owner auditId={auditId} processId={processId} stakeholders={stakeholders} owner={owner}/>{participants.length?<div className="operations-system-chips">{participants.map(p=><div className="operations-system-chip" key={p.id}><span><strong>{p.name}</strong>{p.role?` · ${p.role}`:''}</span><form action={unlinkStakeholderFromProcessAction}><Ids auditId={auditId} processId={processId} stakeholderId={p.id}/><button aria-label={`Desassociar ${p.name}`} className="project-icon-button"><Unlink size={13}/></button></form></div>)}</div>:<div className="operations-steps-empty"><strong>Sem participants associados.</strong></div>}<div className="admin-grid-2"><Link auditId={auditId} processId={processId} people={stakeholders.filter(p=>!linked.has(p.id))}/><Create auditId={auditId} processId={processId}/></div></div>}
function Owner({auditId,processId,stakeholders,owner}:{auditId:string;processId:string;stakeholders:Person[];owner:Person|null}){const[state,action,pending]=useActionState(setProcessOwnerStakeholderAction,initial);return <form action={action} className="operations-system-associate"><Ids auditId={auditId} processId={processId}/><label className="manual-intake-admin-field"><span>Process owner</span><select className="admin-input" defaultValue={owner?.id??''} name="stakeholderId"><option value="">No formal owner</option>{stakeholders.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="admin-button admin-button-muted" disabled={pending}>Guardar owner</button>{state.error?<p className="project-form-error">{state.error}</p>:null}</form>}
function Link({auditId,processId,people}:{auditId:string;processId:string;people:Person[]}){const[state,action,pending]=useActionState(linkStakeholderToProcessAction,initial);return <form action={action} className="operations-system-associate"><Ids auditId={auditId} processId={processId}/><label className="manual-intake-admin-field"><span>Associar participant</span><select className="admin-input" disabled={!people.length} name="stakeholderId" required><option value="">Selecionar…</option>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><button className="admin-button admin-button-muted" disabled={pending||!people.length}>Associar</button>{state.error?<p className="project-form-error">{state.error}</p>:null}</form>}
function Create({auditId,processId}:{auditId:string;processId:string}){const[state,action,pending]=useActionState(createAndLinkStakeholderToProcessAction,initial);const ref=useRef<HTMLFormElement>(null);useEffect(()=>{if(state.success)ref.current?.reset()},[state]);return <form action={action} className="operations-system-associate" ref={ref}><Ids auditId={auditId} processId={processId}/><label className="manual-intake-admin-field"><span>Criar participant</span><input className="admin-input" name="name" placeholder="Name" required/></label><label className="manual-intake-admin-field"><span>Role</span><input className="admin-input" name="role"/></label><button className="admin-button" disabled={pending}><Plus size={14}/>Criar e associar</button>{state.error?<p className="project-form-error">{state.error}</p>:null}</form>}
function Ids({auditId,processId,stakeholderId}:{auditId:string;processId:string;stakeholderId?:string}){return <><input name="auditId" type="hidden" value={auditId}/><input name="processId" type="hidden" value={processId}/>{stakeholderId?<input name="stakeholderId" type="hidden" value={stakeholderId}/>:null}</>}
