'use client';

import Link from 'next/link';
import { useActionState, useEffect, useRef } from 'react';
import { ArrowUpRight, Plus, Trash2 } from 'lucide-react';
import { createAutomationOpportunityAction, deleteAutomationOpportunityAction, type OpportunityActionState } from '@/lib/operations-audits/actions';

const initial:OpportunityActionState={success:false};
type Opportunity={id:string;title:string|null;problem:string;status:string};

export function ProcessOpportunities({auditId,processId,opportunities}:{auditId:string;processId:string;opportunities:Opportunity[]}){const[state,action,pending]=useActionState(createAutomationOpportunityAction,initial),ref=useRef<HTMLFormElement>(null);useEffect(()=>{if(state.success)ref.current?.reset()},[state]);return <div className="operations-systems"><form action={action} className="operations-process-form" ref={ref}><Ids auditId={auditId} processId={processId}/><div className="admin-grid-2"><label className="manual-intake-admin-field"><span>Opportunity title *</span><input className="admin-input" name="title" required/></label><label className="manual-intake-admin-field"><span>Problem *</span><input className="admin-input" name="problem" required/></label></div><input name="status" type="hidden" value="DISCOVERED"/><div className="operations-process-form-actions"><button className="admin-button" disabled={pending}><Plus size={14}/>Criar oportunidade</button></div>{state.error?<p className="project-form-error">{state.error}</p>:null}{state.success&&state.opportunityId?<p className="admin-row-meta">Oportunidade criada. <Link className="admin-link" href={`/admin/operations-audits/${auditId}/processes/${processId}/opportunities/${state.opportunityId}`}>Abrir detalhe</Link></p>:null}</form>{opportunities.length?<div className="operations-system-list">{opportunities.map(o=><article className="operations-system-row" key={o.id}><div><strong>{o.title??'Untitled opportunity'}</strong><span>{o.problem} · {statusLabel(o.status)}</span></div><div/><div className="operations-step-actions"><Link aria-label="Abrir oportunidade" className="project-icon-button" href={`/admin/operations-audits/${auditId}/processes/${processId}/opportunities/${o.id}`}><ArrowUpRight size={14}/></Link><form action={deleteAutomationOpportunityAction} onSubmit={e=>{if(!window.confirm('Apagar esta oportunidade? A evidência associada será preservada.'))e.preventDefault()}}><Ids auditId={auditId} processId={processId}/><input name="opportunityId" type="hidden" value={o.id}/><button aria-label="Apagar oportunidade" className="project-icon-button operations-step-delete"><Trash2 size={14}/></button></form></div></article>)}</div>:<div className="operations-steps-empty"><strong>Ainda não existem oportunidades.</strong><span>Comece pelo problema observado; o detalhe pode ser enriquecido depois.</span></div>}</div>}
function Ids({auditId,processId}:{auditId:string;processId:string}){return <><input name="auditId" type="hidden" value={auditId}/><input name="processId" type="hidden" value={processId}/></>}
export function statusLabel(value:string){return({DISCOVERED:'Discovered',VALIDATING:'Validating',RECOMMENDED:'Recommended',PILOT_PROPOSED:'Pilot proposed',PILOT_ACCEPTED:'Pilot accepted',IMPLEMENTED:'Implemented',REJECTED:'Rejected'}[value]??value)}
