'use client';

import { useActionState } from 'react';
import { AdminPanel } from '@/components/admin/AdminPrimitives';
import { retryReportDeliveryAction, sendAuditReportAction, sendPilotReportAction } from '@/lib/operations-audits/actions';

type Delivery = { id: string; reportType: string; status: string; recipientEmail: string; recipientName: string | null; subject: string; generatedAt: string; sentAt: string | null; sentBy: string | null; fileName: string; fileSizeBytes: number; failureReason: string | null };
const initial: any = { success: false };
const label = (s: string) => s.replaceAll('_', ' ');

export function ReportDeliveryPanel({ auditId, pilot, pilotId, defaultSubject, defaultMessage, history, warning }: { auditId: string; pilot?: { processId: string; opportunityId: string }; pilotId?: string; defaultSubject: string; defaultMessage: string; history: Delivery[]; warning?: string }) {
  const action = pilot ? sendPilotReportAction : sendAuditReportAction;
  const [state, formAction, pending] = useActionState(action as any, initial);
  return <div className="report-delivery-stack"><AdminPanel title={pilot ? 'Send Pilot Report' : 'Send Audit Report'}><p className="admin-row-text">The generated PDF is stored immutably and the exact same bytes are attached to this email.</p>{warning ? <p className="admin-callout admin-callout-warning">{warning}</p> : null}<form action={formAction} className="admin-form-grid"><input type="hidden" name="auditId" value={auditId}/>{pilot ? <><input type="hidden" name="processId" value={pilot.processId}/><input type="hidden" name="opportunityId" value={pilot.opportunityId}/><input type="hidden" name="pilotId" value={pilotId ?? ''}/></> : null}<label>Recipient name<input name="recipientName" maxLength={160}/></label><label>Recipient email<input name="recipientEmail" type="email" required maxLength={320}/></label><label className="admin-form-span-2">Subject<input name="subject" defaultValue={defaultSubject} required maxLength={180}/></label><label className="admin-form-span-2">Message<textarea name="message" defaultValue={defaultMessage} required maxLength={10000} rows={5}/></label><div className="admin-form-span-2"><button className="admin-button" type="submit" disabled={pending}>{pending ? 'Sending…' : 'Send Report'}</button>{state.error ? <p className="admin-error">{state.error}</p> : null}{state.success ? <p className="admin-success">{state.message}</p> : null}</div></form></AdminPanel><AdminPanel title="Delivery History"><table className="admin-table"><thead><tr><th>Status</th><th>Recipient</th><th>Generated</th><th>Sent</th><th>File</th><th/></tr></thead><tbody>{history.length ? history.map(row => <tr key={row.id}><td>{label(row.status)}{row.failureReason ? <small title={row.failureReason}> · failed</small> : null}</td><td>{row.recipientName ? `${row.recipientName} · ` : ''}{row.recipientEmail}</td><td>{new Date(row.generatedAt).toLocaleString()}</td><td>{row.sentAt ? new Date(row.sentAt).toLocaleString() : '—'}</td><td><a href={`/admin/operations-audits/${auditId}/report-deliveries/${row.id}/file`} download>{row.fileName}</a></td><td>{row.status === 'FAILED' ? <RetryButton auditId={auditId} deliveryId={row.id}/> : null}</td></tr>) : <tr><td colSpan={6}>No deliveries yet.</td></tr>}</tbody></table></AdminPanel></div>;
}

function RetryButton({ auditId, deliveryId }: { auditId: string; deliveryId: string }) { const [state, action, pending] = useActionState(retryReportDeliveryAction, initial); return <form action={action}><input type="hidden" name="auditId" value={auditId}/><input type="hidden" name="deliveryId" value={deliveryId}/><button className="admin-button admin-button-muted" disabled={pending}>{pending ? 'Retrying…' : 'Retry'}</button>{state.error ? <span className="admin-error">{state.error}</span> : null}</form>; }
