import Link from 'next/link';
import { notFound } from 'next/navigation';
import { ArrowLeft } from 'lucide-react';
import { AdminBadge } from '@/components/admin/AdminBadge';
import { AdminPanel } from '@/components/admin/AdminPrimitives';
import { OpportunityDetail } from '@/components/admin/operations-audits/OpportunityDetail';
import { OpportunityEvaluation } from '@/components/admin/operations-audits/OpportunityEvaluation';
import { OpportunityScoreSummary } from '@/components/admin/operations-audits/OpportunityScoreSummary';
import { OpportunityScoreBreakdown } from '@/components/admin/operations-audits/OpportunityScoreBreakdown';
import { OpportunityDecision } from '@/components/admin/operations-audits/OpportunityDecision';
import { requireAdmin } from '@/lib/admin/auth';
import { getAutomationOpportunityById, getOpportunityPortfolio, getPilotProposalByOpportunity } from '@/lib/operations-audits/service';
import { getActiveAutomationScoringModel } from '@/lib/operations-audits/scoring-service';
import { dimensionMetadata,type ScoringModelConfig } from '@/lib/operations-audits/scoring';
import { isScoreSnapshotStale, readScoreSnapshotDimensions, readScoreSnapshotSummary } from '@/lib/operations-audits/score-snapshot';
import { classifyOpportunityDecision } from '@/lib/operations-audits/matrix-framework';
import { rankOpportunityPortfolio } from '@/lib/operations-audits/portfolio-ranking';

export default async function OpportunityPage({params}:{params:Promise<{id:string;processId:string;opportunityId:string}>}){
  await requireAdmin();
  const{id:auditId,processId,opportunityId}=await params;
  const [opportunity,model,portfolioRows,pilot]=await Promise.all([getAutomationOpportunityById(auditId,processId,opportunityId),getActiveAutomationScoringModel(),getOpportunityPortfolio(auditId),getPilotProposalByOpportunity(auditId,processId,opportunityId)]);
  if(!opportunity)notFound();
  const baselines=opportunity.process.baselines.map(metric=>({...metric,numericValue:metric.numericValue?.toString()??null}));
  const serializableOpportunity={id:opportunity.id,title:opportunity.title,problem:opportunity.problem,currentState:opportunity.currentState,proposedOutcome:opportunity.proposedOutcome,automationConcept:opportunity.automationConcept,expectedFutureState:opportunity.expectedFutureState,status:opportunity.status,recommendation:opportunity.recommendation,bottleneckLinks:opportunity.bottleneckLinks,baselineLinks:opportunity.baselineLinks.map(link=>({...link,baseline:{...link.baseline,numericValue:link.baseline.numericValue?.toString()??null}}))};
  const parsedSnapshot=parseSnapshot(opportunity.scoreSnapshot),stale=isScoreSnapshotStale(opportunity.assessment,opportunity.scoreSnapshot),summary=readScoreSnapshotSummary(opportunity.scoreSnapshot),dimensions=readScoreSnapshotDimensions(opportunity.scoreSnapshot),decisionFramework=classifyOpportunityDecision({businessValueScore:dimensions?.businessValue?.score??null,feasibilityScore:dimensions?.feasibility?.score??null,confidence:summary?.confidence??null,coverage:summary?.coverage??null,scoreState:!opportunity.scoredAt?'UNSCORED':summary?.score===null?'SCORED_NULL':stale?'STALE':'CURRENT'}),rank=rankOpportunityPortfolio(portfolioRows.map(row=>({id:row.id,score:readScoreSnapshotSummary(row.scoreSnapshot)?.score??null}))).find(row=>row.id===opportunity.id)?.globalRank??null;
  const decisionContext={score:summary?.score===null||!summary?'Not scored':`${summary.score} / 100`,confidence:summary?`${Math.round(summary.confidence)}%`:'—',coverage:summary?`${Math.round(summary.coverage)}%`:'—',rank:rank===null?'—':`#${rank}`,matrix:decisionFramework,strategicFit:opportunity.strategicFit??'Not defined',status:opportunity.status};
  const context={bottlenecks:opportunity.bottleneckLinks.map(x=>({description:x.bottleneck.description})),baselines:opportunity.baselineLinks.map(x=>({label:x.baseline.label,value:x.baseline.numericValue?.toString()??x.baseline.textValue,unit:x.baseline.unit,period:x.baseline.period,evidenceQuality:x.baseline.evidenceQuality})),systems:opportunity.process.systems.map(x=>({name:x.system.name,apiAvailable:x.system.apiAvailable,exportAvailable:x.system.exportAvailable,integrationDifficulty:x.system.integrationDifficulty})),dataSources:opportunity.process.dataSources.map(x=>({name:x.dataSource.name,structure:x.dataSource.structure,accessibility:x.dataSource.accessibility,quality:x.dataSource.quality===null?null:String(x.dataSource.quality),sensitivity:x.dataSource.sensitivity}))};
  return <div className="admin-page-grid"><AdminPanel title={opportunity.title??'Untitled opportunity'} subtitle={`${opportunity.process.name} · ${opportunity.audit.name}`} action={<div className="admin-filters"><AdminBadge tone="blue">{opportunity.status}</AdminBadge><Link className="admin-button admin-button-muted" href={`/admin/operations-audits/${auditId}/processes/${processId}#opportunities`}><ArrowLeft size={14}/>Voltar ao processo</Link></div>}><p className="admin-row-text">{opportunity.problem}</p></AdminPanel><AdminPanel title="Opportunity detail" subtitle="Defina a hipótese de automação e ligue-a à evidência observada."><OpportunityDetail auditId={auditId} processId={processId} opportunity={serializableOpportunity} bottlenecks={opportunity.process.bottlenecks} baselines={baselines}/></AdminPanel><AdminPanel id="evaluation" title="Evaluation" subtitle="Capture a avaliação e a qualidade da evidência. O score só muda através da ação explícita abaixo.">{model?<OpportunityEvaluation auditId={auditId} processId={processId} opportunityId={opportunity.id} model={{id:model.id,name:model.name,version:model.version,config:model.config as ScoringModelConfig}} assessment={opportunity.assessment} context={context}/>:<p className="project-form-error">Não existe um scoring model ativo para esta evaluation.</p>}</AdminPanel><AdminPanel id="score" title="Score Summary" subtitle="Current decision-support snapshot. Score, evidence confidence and coverage remain separate."><OpportunityScoreSummary auditId={auditId} processId={processId} opportunityId={opportunity.id} snapshot={parsedSnapshot?.view??null} stale={stale} hasAssessment={Boolean(opportunity.assessment)}/></AdminPanel><AdminPanel id="breakdown" title="Score Breakdown" subtitle="Explainability from the last persisted score snapshot; no score is recalculated here."><OpportunityScoreBreakdown snapshot={opportunity.scoreSnapshot} stale={stale}/></AdminPanel><AdminPanel id="decision" title="Final Decision" subtitle="Human decision only. Analytical context remains separate from the decision."><OpportunityDecision auditId={auditId} processId={processId} opportunityId={opportunity.id} decision={opportunity.decision} decisionRationale={opportunity.decisionRationale} decisionOwner={opportunity.decisionOwner} decidedAt={opportunity.decidedAt?.toISOString()??null} nextStep={opportunity.nextStep} context={decisionContext}/>{opportunity.decision==='PROCEED_TO_PILOT' ? <Link className="admin-button" href={`/admin/operations-audits/${auditId}/processes/${processId}/opportunities/${opportunityId}/pilot`}>{pilot ? 'View Pilot Proposal' : 'Create Pilot Proposal'}</Link> : null}</AdminPanel></div>
}

function parseSnapshot(raw:unknown){if(!raw||typeof raw!=='object')return null;const snapshot=raw as {assessment?:unknown;scoredAt?:unknown;model?:{name?:unknown;version?:unknown};result?:{opportunityScore?:unknown;confidenceScore?:unknown;coverage?:unknown;dimensions?:Record<string,{score?:unknown;coverage?:unknown}>}};if(typeof snapshot.scoredAt!=='string'||!snapshot.model||typeof snapshot.model.name!=='string'||typeof snapshot.model.version!=='number'||!snapshot.result||typeof snapshot.result.confidenceScore!=='number'||typeof snapshot.result.coverage!=='number')return null;const dimensions=Object.entries(snapshot.result.dimensions??{}).map(([key,value])=>({key,label:dimensionMetadata[key as keyof typeof dimensionMetadata]?.label??key,score:typeof value.score==='number'?value.score:null,coverage:typeof value.coverage==='number'?value.coverage:0}));return{assessment:snapshot.assessment,view:{score:typeof snapshot.result.opportunityScore==='number'?snapshot.result.opportunityScore:null,confidence:snapshot.result.confidenceScore,coverage:snapshot.result.coverage,modelName:snapshot.model.name,modelVersion:snapshot.model.version,scoredAt:snapshot.scoredAt,dimensions}}}
