-- Add contract versioning and audit metadata for Phase 4 controls.
ALTER TABLE "ContractVersion" ADD COLUMN "versionLabel" TEXT;
ALTER TABLE "ContractVersion" ADD COLUMN "statusAtGeneration" "ContractStatus";
ALTER TABLE "ContractVersion" ADD COLUMN "changeReason" TEXT;

ALTER TYPE "ContractActivityType" ADD VALUE IF NOT EXISTS 'CONTRACT_PDF_GENERATED';
ALTER TYPE "ContractActivityType" ADD VALUE IF NOT EXISTS 'CONTRACT_PDF_REGENERATED';
ALTER TYPE "ContractActivityType" ADD VALUE IF NOT EXISTS 'CONTRACT_REOPENED';
ALTER TYPE "ContractActivityType" ADD VALUE IF NOT EXISTS 'CONTRACT_REVISION_CREATED';
ALTER TYPE "ContractActivityType" ADD VALUE IF NOT EXISTS 'CONTRACT_LOCKED';
ALTER TYPE "ContractActivityType" ADD VALUE IF NOT EXISTS 'CONTRACT_UNLOCKED';
ALTER TYPE "ContractActivityType" ADD VALUE IF NOT EXISTS 'CONTRACT_READY_TO_SEND';
ALTER TYPE "ContractActivityType" ADD VALUE IF NOT EXISTS 'CONTRACT_CANCELLED';
ALTER TYPE "ContractActivityType" ADD VALUE IF NOT EXISTS 'CONTRACT_EXPIRED';
ALTER TYPE "ContractActivityType" ADD VALUE IF NOT EXISTS 'CONTRACT_SIGNED';
